#!/bin/bash
# Check inputs
check_port(){
if ! [ "$1" -eq "$1" >& /dev/null ];then
  return 1
else
	if [ $1 -lt 65536 ]; then
		return 0
	else
		return 1
	fi
fi
}

setup_forwarding(){
exit
}

if [ $# -ne 3 ]; then
  echo "Please specify target qube, tcp or udp, and target port"
  exit
fi
qvm-check -q $1 2>/dev/null
if [ "$?" -ne 0 ];then
  echo "$1 is not the name of any qube"
  exit
else
	qube_name=$1
fi
if [ "$2" != "tcp" -a "$2" != "udp" ]; then
  echo "Specify tcp or udp"
  exit
else
	proto=$2
fi
check_port $3
if [ $? -ne 0 ]; then
  if !  grep -q -w ^$3\  /etc/services  ; then
    echo "Specify usable port number"
    exit
  else
    portnum=$( getent services $3 |awk '{split($2,a,"/");print a[1]}')
    check_port $portnum
    if [ $? -ne 0 ]; then
      echo "Specify usable port number"
      exit
    fi
  fi
else
portnum=$3
fi

# Get all netvms
declare -a netvms
declare -a ips
declare -a external_ips
hop=0
IFS='|' read -r netvms[$hop] ips[$hop] <<< $(qvm-ls $qube_name --raw-data -O netvm,IP)
while [ ${netvms[hop]} != "-" ]
do
  ((hop++))
  IFS='|' read -r netvms[$hop] ips[$hop] <<< $(qvm-ls ${netvms[$hop-1]} --raw-data -O netvm,IP)
done
if [ $hop -eq 0 ]; then
	echo "$qube_name is not network connected"
  echo "Cannot set up a tunnel"
	exit
fi

# Check last hop has external IP address 
readarray -t external_ips < <( qvm-run -p ${netvms[$hop-1]} "ip -4 -o a|grep -wv 'lo\|vif[0-9]'"|awk '{print $2,$4}')
#readarray -t external_ips < <( qvm-run -p ${netvms[$hop-1]} "ip -4 -o a|grep -wv 'vif[0-9]'"|awk '{print $2,$4}')
num_ifs=${#external_ips[@]}
if [ $num_ifs -eq 1 ]; then
  interface=0
elif [ $num_ifs -gt 1 ]; then
  echo "${netvms[$hop-1]} has more than 1 external interface"
  echo "Which one do you want to use?"
  for i in $(seq $num_ifs)
  do
    echo "$i. ${external_ips[$i-1]}"
  done
  read interface
  if ! [ "$interface" -eq "$interface" ] 2> /dev/null; then
    echo "No such interface"
    exit
  elif [ $interface -gt $num_ifs ] || [ $interface -lt 1 ]; then
    echo "No such interface"
    exit
  fi
  ((interface--))
else
  echo "${netvms[$hop-1]} does not have an external interface"
  echo "Cannot set up a tunnel"
  exit
fi

# Create tunnel
qvm-run -u root $qube_name "nft insert rule filter INPUT iifname eth0 -p $proto --dport $portnum accept"
